### ISSUE TITLE
davide-alt

### ISSUE THREAD

**Issue by davide-alt** [Mirinsoft/Debotnet#1]
Hi, After reading Ghacks article on your app I decided to try it out and just wanted to let you know that Kaspersky Internet Protection flags Debotnet as **PDM:Trojan.Win32.Generic;Debotnet** -  I uploaded debotnet.exe to Virustotal.com and here are the results:

24.12.2019 16.16.16;**Detected malware;PDM:Trojan.Win32.Generic**;Debotnet;c:\users\user\documents\windows10 spying\debotnet\debotnet.exe;12/24/2019 16:16:16

**VirusTotal results:**
![firefox_2019-12-24_17-48-51](https://user-images.githubusercontent.com/59206646/71420468-c5d01900-2675-11ea-84c7-b19d61cdddcc.png)

**Steps to reproduce:**
- Download Debotnet
- Extract and Scan for virus - results clean
- run Debotnet.exe. Select and Run scripts 
- KIS notifies malware running

I have added Debotnet to 'Trusted apps' but after seeing VirusTotal's results it has left me uneasy. Of course, I have the option to not use Debotnet but I believe it is being flagged because it is tampering with protected system files and therefore suspicious.

Please, do not think I am questioning your integrity or trustworthiness. Only trying to bring your attention to this issue and would appreciate your advice.

Many Thanks,

davide-alt

**Comment by iMirin** [comment]
Hi davide,

I have already seen this and the application itself has no scripts embedded, nor other malicious code.
All available scripts can be viewed with a simple text editor and are completely open source (the app itself is currently closed). Internally some known and simple Windows API is used to control the command prompt, powershell, access to registry etc and for capturing the console output. 

Partly the code is based on some of my other applications (CloneApp and Cleanmgr+) and they do not report false positives. 

I have the bad suspicion that here also possibly wording in RAM plays a role for AV engines.  I'll take on the case and hope to get better results in upcoming versions. Some engines reports "Malicious" or "Suspicious" and "Unsafe" This is because the application is relatively unknown. The first public beta has been released yesterday.

Merry Christmas and regards from Germany
Belim

**Comment by davide-alt** [comment]
Hi Belim,

Thank you very much for your very prompt and detailed response. I have white-listed the app on KIS and have run it again with no issues. Also downloaded Cleanmgr+. Thanks again for your help much appreciated.

Merry Christmas and Best wishes for the New Year
Davide
