### ISSUE TITLE
not working on my side

### ISSUE THREAD

**Issue by Wheel-Of-Fate** [mirinsoft/debotnet#11]
1- removed apps are still exist in the store and they are re-downloading after opening store. tested on (Windows 10 Pro build 1909)
2- i believe that there are many outdated scripts since you have many old names in the list for example "get started app" is called "Microsoft tips" now.
3- you forgot to add "don't include drivers in windows update".
4- The GUI is messy.
5- some scripts failed to restore apps/settings.
well looks like i will have to use power shell and group policy for now.
how about to create a script to remove all apps except "Store" and "Shell Experience Host"? i believe this give the users more control over the apps since they can go to store and re download the only needed apps
Out of Curiosity did you test these scripts one by one?
because i see that most of them manipulate registry entries but they got no effect in group policy (i refer to Computer Configuration).
thanks for your effort and good luck with the project.

**Comment by Belim** [comment]
Hi,

1. After a fresh Windows Install, you'll will have to download all app store updates too, before you can uninstall them. Otherwise they're going to be re-installed as you may noticed.
2. Yes you're right. Microsoft Tipps is the new Microsoft.Getstarted. This will be fixed, Thank you! Such hints definitely help me more than "not/nothing working on my side"
3. What do you mean here?
4. Yes, you can not please everyone. What bothers you? If you want it to be simpler, then you have to use some of these countless apps that only offer the two options "Switch: On/Off". But you find PowerShell easier to use at all?
5. Scripts from the category "bloatware", e.g. Removing built-in apps, does not offer such an restore option. Of course, you could add it by yourself.
Most of the GPO changes, creates or modifies registry values in HKCU or HKLM hive. Some of the security settings (e.g. User rights, Password Policy etc.) are not stored in registry keys and in databases (secedit.sdb), but these are not touched by Debotnet. It's all good here, every other app works on same level. You could use GPSearch resource to get corresponding keys  https://gpsearch.azurewebsites.net or https://getadmx.com
And yes, every script is put through its paces several times.

Regards
Belim

**Comment by Wheel-Of-Fate** [comment]
> Hi,
> 
> 1. After a fresh Windows Install, you'll will have to download all app store updates too, before you can uninstall them. Otherwise they're going to be re-installed as you may noticed.
> 2. Yes you're right. Microsoft Tipps is the new Microsoft.Getstarted. The app package still holds the name "Microsoft.Getstarted" The double script will be removed, Thank you! Such hints definitely help me more than "not/nothing working on my side"
> 3. What do you mean here?
> 4. Yes, you can not please everyone. What bothers you? If you want it to be simpler, then you have to use some of these countless apps that only offer the two options "Switch: On/Off". But you find PowerShell easier to use at all?
> 5. Scripts from the category "bloatware", e.g. Removing built-in apps, does not offer such an restore option. Of course, you could add it by yourself.
>    Most of the GPO changes, creates or modifies registry values in HKCU or HKLM hive. Some of the security settings (e.g. User rights, Password Policy etc.) are not stored in registry keys and in databases (secedit.sdb), but these are not touched by Debotnet. It's all good here, every other app works on same level. You could use GPSearch resource to get corresponding keys  https://gpsearch.azurewebsites.net or https://getadmx.com
>    And yes, every script is put through its paces several times.
> 
> Regards
> Belim

'Don't Include Drivers In Windows Update' is a an option buried deep inside W10 which stops windows update from downloading any drivers because this is could cause bugs.
Yea i find power shell extremely easy since there is only one command which can remove all Apps even from the store. besides i find group policy options are very clear too because i used to search & tinker around stuff which is fun to do.
Best Regards

**Comment by Belim** [comment]
I've added another script for disabling automatic delivery of driver updates through Windows update
https://github.com/mirinsoft/debotnet/blob/master/scripts/No%20more%20forced%20driver%20updates.ds1

The GUI provides filtering of tweaks. Not as you describe it, but you can create own categories in script folder and browse them in Navigation panel > browse > all/my scripts/slim etc.
This was done with intention by me for better automation, so that everyone can create and compile his scripts, put them in a category, and press "run" (in best case via CLI https://github.com/mirinsoft/debotnet/wiki/Command-line)
