### ISSUE TITLE
Suspicious?

### ISSUE THREAD

**Issue by masikszabi** [mirinsoft/debotnet#13]
Hi, 4 engines on Virustotal.com detected the Debotnet.exe as malicious (SecureAge APEX, Qihoo-360, Endgame and Trapmine) What could be the reason?

**Comment by Belim** [comment]
Hi,

"Malicious" or "Suspicious" and "Unsafe" is only an evaluation score because the application and file is relatively unknown. 

This has also been discussed here https://github.com/mirinsoft/debotnet/issues/4
and somewhat more detailed here https://github.com/mirinsoft/debotnet/issues/1

The false positives rates have been reduced to a minimum if not even zero if you ignore the three above. The flag from Qihoo-360 is new but definitely a false positive and does not give me any more headcaches.

I can recommend you this blog entry from NirSoft regarding AV Companies and false positives
http://blog.nirsoft.net/2009/05/17/antivirus-companies-cause-a-big-headache-to-small-developers/

**Comment by masikszabi** [comment]
Hi Belim,

All clear now and I'm already using it. 
Thank you for your quick reply.
