### ISSUE TITLE
Script description is not seen after running 1 or more scripts

### ISSUE THREAD

**Issue by xypha** [mirinsoft/debotnet#22]
version 0.5.2
- clicking on a script enables the display of its description on the right side
- after running a script, the description is replaced by script execution commandline/powershell information
- once this is complete, clicking on a script fails to display its description and I am forced to closed and reopen the program!

**Comment by Belim** [comment]
Hi,

i can partially confirm this. After using the global "Run", the "<" link should appear left to "Run", which allows you to clear the status log. This will be fixed in coming release.

As workaround you can also make a right-click > log/status-window > press "clear", which will hide the log window

Thank you.
Belim

**Comment by Belim** [comment]
Fixed in v0.5.3 @https://github.com/mirinsoft/debotnet/releases/tag/0.5.3
