### ISSUE TITLE
No more forced driver updates doesn't work

### ISSUE THREAD

**Issue by grinch1985** [mirinsoft/debotnet#32]
fresh install of windows 10 pro 64 bit 1909 with latest updates, ran debotnet offline, ran script no more forced driver updates and no more forced updates, restarted, uninstalled display driver, restarted, then immediately windows started updating the display driver...

**Comment by Belim** [comment]
Some minor optimizations has been added to release 0.6.0
https://github.com/mirinsoft/debotnet/releases/tag/0.6.0

What happens if you do it in the Group policy by enabling "Do not include drivers with Windows Updates" under  Local Computer Policy  > Computer Configuration/Administrative Templates/Windows Components/Windows Update

It appears that disabling driver updates does not work anymore with >=1903

I've found this
https://www.askwoody.com/2019/is-there-a-way-to-tell-the-win10-1903-upgrade-routine-to-leave-your-drivers-alone/
