### ISSUE TITLE
[antivirus] detected as trojan

### ISSUE THREAD

**Issue by cubakcabak** [mirinsoft/debotnet#4]
mcafee virusscan enterprise detected debotnet as "Artemis!43FCEF7F1D44" trojan

**Comment by iMirin** [comment]
Hi,

it is 100% a false positive. Mcafee is particularly difficult to handle and reports it very easily.
Currently the false positive detection rate is by 3-7/72 AV engines.  Half of it flags Debotnet as  "Malicious" or "Suspicious" and "Unsafe" This is because the application is relatively unknown.
It has been also discussed here https://github.com/mirinsoft/debotnet/issues/1

If you want to help others and me, please report it as a false positive to Mcafee.

Many thanks
Belim

**Comment by iMirin** [comment]
It's currently not anymore flagged by McAfee.
https://www.virustotal.com/gui/file/a0178c42646452f658181dea7f045ded9d80f4ce4f949f81a8cb12ed1f0fd007/detection
