### ISSUE TITLE
Almost Blank Screen After System Restart

### ISSUE THREAD

**Issue by dmacssn675** [mirinsoft/debotnet#43]
I ran the remove default apps (bloatware) and restarted my computer. When I restarted debotnet, it shows an almost blank screen. I unpacked it from the zip file again and restarted, with the same result. At screen shot of the window is attached.
![Debotnet Window](https://user-images.githubusercontent.com/62912509/77967005-3492c300-72b2-11ea-8f52-7c4eb53ec6ab.jpg)

**Comment by Belim** [comment]
Where exactly did you start the application from? Where was it unpacked? Please check the comments section below this article. 
http://www.mirinsoft.com/blog/18-debotnet/17-major-release-of-debotnet-0-7-pegasos-out

A user has the same problem and run it from  C:\Program Files\<user>\Debotnet 
without elevated rights, so the access has been redirected to 
C:\Users\<user>\AppData\Local\**VirtualStore**\Program Files\Mirinsoft\Debotnet\...

The UI could not be drawn in your case. I guess the problem could be anyway fixed by **deleting debotnet-settings.txt file in bin folder** of Debotnet

If you can answer the questions above I can probably fix the problem with the next version

**Comment by dmacssn675** [comment]
Thanks for the reply. I am not running it from C:\Program Files or other
system directory. However, resetting the settings file as described in the
comments you referenced fixed it.

Thanks again,

Dave

**Comment by Echopox** [comment]
I am running 7.5 and getting the same thing. I am running the application from a desktop folder.

**Comment by Belim** [comment]
I've got it. Will be fixed in upcoming release and already in the next Nightly coming today 20:00 - 22pm

**Comment by Belim** [comment]
Nighlty 0.7.520 is on.
https://www.mirinsoft.com/debotnet-nightly

Please check again

**Comment by Belim** [comment]
Fixed in release 0.7.6 
https://github.com/mirinsoft/debotnet/releases/tag/0.7.6
